In [12]:
import numpy

In [3]:
n=numpy.arange(27)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [7]:
n.reshape(3,3,3) #3D array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [8]:
m = numpy.asarray([[123,12,123,12,33],[],[]]) #converts list to numpy array

In [9]:
m

array([[123, 12, 123, 12, 33], [], []], dtype=object)

In [11]:
type(m)

numpy.ndarray

In [1]:
import cv2

In [6]:
img_gray=cv2.imread("smallgray.png",0) #read image (0 in gray scale, 1 in BGR)
img_gray

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [5]:
cv2.imwrite("newsmallgray.png",img_gray) #creates new image from numpyarray

True

In [8]:
img_gray[0:2,2:4] #slice numpyarray

array([[104, 121],
       [255, 255]], dtype=uint8)

In [9]:
for i in img_gray: #prints rows or img_gray.T for transposed
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [10]:
for i in img_gray.flat: #goes throught each value one at a time
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [13]:
ims = numpy.hstack((img_gray,img_gray)) # stacks 2 or more numpyarrays horiznontally

In [14]:
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [15]:
ims = numpy.vstack((img_gray,img_gray)) # stacks arrays vertically
print(ims)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [19]:
lst=numpy.vsplit(ims,3)  #split numpyarray, produces a list
lst

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182],
        [187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]